# Set config for brush, squeegee, flow and vacuum
# Request: config set
# Respond: None
# Service call should return false if config values out of defined range
######################################################
# Data Description
# configs   Range    Meaning
#   all       0        OFF
#   all      -1      Remain Current State
#lock_wheel   1       Lock
#brush_down   1       Down
#  brush    1-100    On & speed scale from min to max   
# squeegee    1        ON  
#  flow     1-100    On & power scale from min to max 
#  vacuum   1-100    On & power scale from min to max
######################################################
# Example
# brush = -1
# squeegee = 1
# flow = 50
# vacuum = 0
# Means brush state remain unchange, turn on squeegee, set flow power to 50 and close vacuum
int8 lock_wheel
int8 brush    
int8 squeegee
int8 flow
int8 vacuum
---
