#刷盘升起放下 -- 参考UpDown.msg
uint8 BRUSH_DISC_STAT = 1
#刷盘转速 -- 参考Speed.msg
uint8 BRUSH_DISC_SPEED = 2
#水泵速度 -- 参考Speed.msg
uint8 WATER_PUMP_SPEED = 3
#吸水扒升起放下 -- 参考UpDown.msg
uint8 WATER_SUCK_STAT = 5
#吸水扒速度 -- 参考Speed.msg
uint8 WATER_SUCK_SPEED = 6
#手动作业开始,结束 -- 没有值
uint8 MANUAL_START = 7
uint8 MANUAL_STOP = 8
#播放声音 -- 没有值
uint8 SOUND_PLAY = 9
#行进速度--手动作业界面 -- 浮点数，单位米/秒
#行进速度--清扫记录界面 -- 参考Speed.msg
uint8 WALK_SPEED = 10
#行进方向--参考Direction.msg
uint8 WALK_DIRECTION = 11
