cleaning_costmap:
  plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 3.0
  publish_frequency: 1.0
  static_map: true
  rolling_window: false
  resolution: 0.05   #0.05
  transform_tolerance: 0.5
  map_type: costmap
  map_topic: move_base_flex/global_costmap/costmap

  obstacles:
    track_unknown_space: true

  inflation:
    inflation_radius: 0.75
    cost_scaling_factor: 3.0

cleaning_plan_nodehandle:   
   size_of_cell: 11
